### ISSUE TITLE
Update jobs to studies

### ISSUE THREAD

**Issue by powersaudrey25** [uiowaSEP2024/002_ImagePro#113]
**If this feature request related to a problem? Please describe.**

We will be using the term "study" instead of "job". Our database schema needs to reflect this.

**Alternatives Considered If Applicable**

None

**Rationale**

The use of "study" makes this app more catered toward medical imaging companies and hospitals.

**Implementation Ideas**

New migrations will need to be added to rename tables, columns, etc.
All references to "job" in the backend will need to be refactored to reference "study"

**Additional Context**

In the updated ER diagram for the study table there does not exist a provider_study_id, this was an error and it will need to exist.

**Comment by zmorris248** [comment]
I tested the full app on branch 113-jobs-to-studies. Everything seems to be functioning, the only thing is there are a few runtime errors on the front end. One happens when you go to 'Analytics' and the other when you click on a specific 'Study' on your studies page. Also, one of the pictures on the front page isn't registering.
