### ISSUE TITLE
Orthanc Reciever Agent to download stable studies

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [uiowaSEP2024/002_ImagePro#118]
If this feature request related to a problem? Please describe.

Our current process for downloading stable instances from our Orthanc DICOM server is manual and time-consuming. This issue becomes apparent when dealing with large datasets or when trying to ensure that only the most stable and verified instances are downloaded for further processing or analysis. An automated or more efficient method of identifying and downloading these instances would significantly improve our workflow, reduce errors, and save time.

Rationale

Implementing a feature that automates the identification and downloading of stable instances from Orthanc would be highly beneficial for several reasons. Firstly, it would streamline our data handling processes, making them more efficient and less prone to error. 

Implementation Ideas
PyOrthanc

Additional Context
Next step in connecting example tool to orthancs

**Comment by mbrzus** [comment]
This issue was significantly expanded. Together with @Ivan-E-Johnson we were able to extend the functionality of the system towards the Sprint 3 Minimum Viable Product.

Here are the new aspects covered under the issue and branch #118

- [x] Setup Example Hospital PACS Server
- [x] Setup Internal System PACS Server
- [x] Setup 2-way connection between servers to send data
- [x] Create an agent listening for incoming data
- [x] Validate Study Stability
- [x] Download data to local system
- [x] Integrate Example Medical Imaging Tool to automatically process the data
- [x] Ensure Example Medical Imaging Tool produces valid DICOM deliverables
- [x] Automatically upload the data to Internal PACS Server in correct study
- [x] Return processed data back to Hospital PACS Server
- [ ] Integrate Logging System and Frontend with the agent

Furthermore, this issue ties to the following user stories:
- #68 
- #61 
- #24
- #35 
- #34
