### ISSUE TITLE
Update user tables

### ISSUE THREAD

**Issue by zmorris248** [uiowaSEP2024/002_ImagePro#126]
**If this feature request related to a problem? Please describe.**

So that we can track information about users pertaining to whether they are a hospital user or provider user and which hospital or provider they are a part of, we want role enum(hospital, provider) added to the users table and a join table for hospital users and a join table for provider users so we know which hospital or provider they are a part of. See ER diagram 2-28-24
**Alternatives Considered If Applicable**

**Rationale**

**Implementation Ideas**

**Additional Context**

**Comment by powersaudrey25** [comment]
Strategy for this issue:

Stage 1 (have done by EOD 2/26):
- change the current enum to have hospital and provider (then we should just be able to add logic to query either the hospital or provider table based on the user's role, no need for actual hospital users and provider users tables, join tables should work fine)
- update seed file to have hospitals and providers 
- update seed file to change roles

_this can all be tested through unit tests no frontend changes will be needed, possibly a few other backend changes to get tests working_

Stage 2:
- update backend to look for hospital instead of customer (backend, trackerapi, internal_servers, brainmask)
- change frontend to look for hospital instead of customer (frontend, cypress)
- add more logic on what a user sees when they log in as a hospital rep vs a provider (talk to michal/ivan)
